# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "gis.lib.metadatacsw"
  tags:
  - "internal"
spec:
  type: "library"
  lifecycle: "production"
  owner: "datadeling_og_distribusjon"
  system: "geonorge"
